version: "3.7"

services:
  telemetry_server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=postgres://postgres:postgres@telemetry_db:5432/postgres?sslmode=disable
    depends_on:
      - telemetry_db
  telemetry_db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=telemetry_db
    depends_on:
      - telemetry_db
