capture:
  video:
    codec: vp8
    ids: [ hd, hq, mq, lq ]
    pipelines:
      hd:
        fps: 25
       # bitrate: 3110400
        gst_encoder: vp8enc
        gst_params:
          end-usage: cbr
          target-bitrate: round((width * height * 3) / 2)
          cpu-used: 4
          threads: 4
          deadline: 1
          undershoot: 95
          keyframe-max-dist: 25
          min-quantizer: 3
          max-quantizer: 32
          buffer-initial-size: round(4 * ((width * height * 3) / 2000))
          buffer-optimal-size: round(5 * ((width * height * 3) / 2000))
          buffer-size: round(6 * ((width * height * 3) / 2000))
      hq:
        fps: 15
       # bitrate: 1555200
        gst_encoder: vp8enc
        gst_params:
          end-usage: cbr
          target-bitrate: round((width * height * 3) / 4)
          cpu-used: 4
          threads: 4
          deadline: 1
          undershoot: 95
          keyframe-max-dist: 25
          min-quantizer: 3
          max-quantizer: 32
          buffer-initial-size: round(4 * ((width * height * 3) / 4000))
          buffer-optimal-size: round(5 * ((width * height * 3) / 4000))
          buffer-size: round(6 * ((width * height * 3) / 4000))
      mq:
        fps: 10
       # bitrate: 1036800
        gst_encoder: vp8enc
        gst_params:
          end-usage: cbr
          target-bitrate: round((width * height) / 2)
          cpu-used: 4
          threads: 4
          deadline: 1
          undershoot: 95
          keyframe-max-dist: 25
          min-quantizer: 3
          max-quantizer: 32
          buffer-initial-size: round(4 * ((width * height) / 2000))
          buffer-optimal-size: round(5 * ((width * height) / 2000))
          buffer-size: round(6 * ((width * height) / 2000))
      lq:
        fps: 5
       # bitrate: 777600
        gst_encoder: vp8enc
        gst_params:
          end-usage: cbr
          target-bitrate: round((width * height * 3) / 8)
          cpu-used: 4
          threads: 4
          deadline: 1
          undershoot: 95
          keyframe-max-dist: 25
          min-quantizer: 3
          max-quantizer: 32
          buffer-initial-size: round(4 * ((width * height * 3) / 8000))
          buffer-optimal-size: round(5 * ((width * height * 3) / 8000))
          buffer-size: round(6 * ((width * height * 3) / 8000))
  screencast:
    enabled: true

server:
  pprof: true

desktop:
  screen: "1920x1080@60"

member:
  provider: "object"
  object:
    admin_password: "admin"
    user_password: "neko"
  # provider: "file"
  # file:
  #   path: "/home/neko/members.json"

session:
  # Allows reconnecting the websocket even if the previous
  # connection was not closed. Can lead to session hijacking.
  merciful_reconnect: true
  # Show inactive cursors on the screen. Can lead to multiple
  # data sent via WebSockets and additonal rendering cost on
  # the clients.
  inactive_cursors: true
  api_token: "neko123"
  cookie:
    # Disabling cookies will result to use Bearer Authentication.
    # This is less secure, because access token will be sent to
    # client in playload and accessible via JS app.
    enabled: false
    secure: false

webrtc:
  icelite: true
  iceservers:
    - urls: [ stun:stun.l.google.com:19302 ]
    #  username: foo
    #  credential: bar
